language: julia
julia:
 - 0.4
 - 0.5
 - nightly
before_install:
 - sudo apt-get -qq update
 - julia -e 'Pkg.clone("git://github.com/blegat/Polyhedra.jl.git")'
 - sudo apt-get install -y python-pip
 - sudo pip install scipy
