language: julia
julia:
    - 0.4
    - 0.5
    - nightly
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); ENV["PYTHON"]=""; Pkg.build("QHull"); Pkg.test("QHull")'
